// ── Connection ─────────────────────────────────────────────────────────────
export const ROBOT_ADDRESS = '10.3.21.2'
export const ROBOT_MDNS = 'roborio-321-frc.local'

/** Set to true to use animated fake data instead of a real NT4 connection. */
export const SIM_MODE = false

/**
 * CALIBRATE_PIVOT: click the pivot bolt on the ROBOT BODY image (side-view.png).
 * Paste the x/y into pivotFraction below, then set to false.
 *
 * CALIBRATE_ARM_PIVOT: shows the arm image alone so you can click the pivot
 * bolt on the ARM image. Paste into armPivotFraction below, then set to false.
 *
 * Run step 1 first, then step 2. Both must be false for normal operation.
 */
export const CALIBRATE_PIVOT     = false
export const CALIBRATE_ARM_PIVOT = false
/** Drag widget handles to set overlay anchor positions. Paste the output into ANCHORS. */
export const CALIBRATE_ANCHORS   = false

// ── NetworkTables topic paths ──────────────────────────────────────────────
// These are generated by Epilogue based on field names in @Logged classes.
// Verify exact paths in AdvantageScope while the robot is running:
//   - Open AdvantageScope → NT4 → expand the /Robot tree.
// The prefix (/Robot) comes from the Epilogue backend configuration in Robot.java.
export const TOPICS = {
  shooter: {
    leftVelocityRpm:         '/Robot/shooter/leftVelocityRotationsPerMinute',
    rightVelocityRpm:        '/Robot/shooter/rightVelocityRotationsPerMinute',
    targetVelocityRadPerSec: '/Robot/shooter/shooterTargetVelocity',
    atSetpoint:              '/Robot/shooter/atSetpoint',
  },
  hood: {
    positionRad:       '/Robot/hood/positionRadians',
    targetPositionRad: '/Robot/hood/targetPositionRadians',
    homed:             '/Robot/hood/homed',
  },
  intakePivot: {
    positionRad:       '/Robot/intakePivot/positionRadians',
    targetPositionRad: '/Robot/intakePivot/targetPositionRadians',
  },
  intakeRollers: {
    velocityRpm: '/Robot/intakeRollers/velocityRotationsPerMinute',
  },
  indexer: {
    velocityRpm: '/Robot/indexer/velocityRotationsPerMinute',
  },
  tunnel: {
    velocityRpm: '/Robot/tunnel/velocityRotationsPerMinute',
    beamBreak:   '/Robot/tunnel/beamBreak',
  },
  vision: {
    leftClimbConnected:       '/Robot/vision/leftClimbCameraConnected',
    rightClimbConnected:      '/Robot/vision/rightClimbCameraConnected',
    leftShooterConnected:     '/Robot/vision/leftShooterCameraConnected',
    rightShooterConnected:    '/Robot/vision/rightShooterCameraConnected',
    leftClimbTargetCount:     '/Robot/vision/leftClimbCameraTargetCount',
    rightClimbTargetCount:    '/Robot/vision/rightClimbCameraTargetCount',
    leftShooterTargetCount:   '/Robot/vision/leftShooterCameraTargetCount',
    rightShooterTargetCount:  '/Robot/vision/rightShooterCameraTargetCount',
  },
  canStatus: {
    tof:              '/Robot/shooter/tofConnected',
    shooterTop:       '/Robot/shooter/topShooterConnected',
    shooterBottom:    '/Robot/shooter/bottomShooterConnected',
    hoodMotor:        '/Robot/hood/hoodMotorConnected',
    hoodCANdi:        '/Robot/hood/hoodCANdiConnected',
    indexer:          '/Robot/indexer/indexerMotorConnected',
    intakeRoller:     '/Robot/intakeRollers/intakeRollerMotorConnected',
    tunnel:           '/Robot/tunnel/tunnelMotorConnected',
    intakePivot:      '/Robot/intakePivot/intakePivotMotorConnected',
    climbMotor:       '/Robot/climb/climbMotorConnected',
    climbPivotMotor:  '/Robot/climb/pivotClimbMotorConnected',
    climbEncoder:     '/Robot/climb/climbEncoderConnected',
    climbPivotEncoder:'/Robot/climb/pivotEncoderConnected',
  },
} as const

// ── Shooter color gradient ─────────────────────────────────────────────────
// Adjust to match the actual max RPM of your shooter.
export const SHOOTER_MAX_RPM = 6000

// ── Hood rotation (front view) ────────────────────────────────────────────
// The hood is drawn as a bar that pivots from its left edge.
// hoodPivot anchor in FrontView ANCHORS sets the hinge position.
// cssRotationAtZero: CSS rotate() value (degrees) when NT angle = 0 rad.
// cssDegreesPerRad: scale + direction. Negate if rotation is backwards.
// widthPercent: length of the hood bar as a % of the image width.
export const HOOD_ARM = {
  cssRotationAtZero: 0,
  cssDegreesPerRad:  -57.296,
  widthPercent:      24,
} as const

// ── Intake arm rotation (side view) ───────────────────────────────────────
// The arm overlay is a full-size PNG (same pixel dimensions as side-view.png)
// with a transparent background — only the arm itself is visible.
// Both images must be captured from the same Onshape camera position.
//
// pivotFraction: where the pivot joint sits within the full image (0–1).
//   Measure it by opening side-view.png in any image editor, hovering over
//   the pivot bolt, and dividing pixel coords by image width/height.
//
// ntAngleRad: the NT topic publishing the current pivot angle in radians.
// cssRotationAtZero: the CSS rotate() value (degrees) when NT angle = 0 rad.
//   Set this by looking at the arm at its zero position and tweaking until
//   the overlay lines up.
// cssDegreesPerRad: scale + direction. Negate if rotation is backwards.
export const INTAKE_ARM = {
  // Where the pivot bolt sits in the ROBOT BODY image (side-view.png).
  // Set via CALIBRATE_PIVOT mode.
  pivotFraction:    { x: 0.6601, y: 0.6812 },

  // Where the pivot bolt sits in the ARM image (side-arm.png).
  // Set via CALIBRATE_ARM_PIVOT mode.
  armPivotFraction: { x: 0.6592, y: 0.6784 }, // ← set this next

  ntAngleRad:        TOPICS.intakePivot.positionRad,
  cssRotationAtZero: 0,       // degrees when NT angle = 0 — tune after both pivots are set
  cssDegreesPerRad:  -57.296, // negate if rotation direction is wrong
} as const
